function DAVOS
% DAVOS: Data Analysis, Visualization, and Outlier-detection Suite
% GUI to process, analyze, and detect anomalies in NASA Valve Current data sets.
scrsz = get(0,'ScreenSize');
f = figure('Visible', 'off', 'Units', 'Normalized', ...
    'OuterPosition',[0 0 1 1], 'Resize', 'off', 'NumberTitle', 'off', 'Color', [1 1 1]);

%Construct the time series plot.
h_timeseries = axes('Units','Normalized','OuterPosition',[0.0,0.5,0.5,0.5], 'Parent', f);
xlabel(h_timeseries, 'Time [a.u.]')
ylabel(h_timeseries, 'Valve current [a.u.]')
title('Time Series Display')

%Construct the auxiliary plot.
h_auxiliary = axes('Units','Normalized','OuterPosition',[0.5,0.5,0.5,0.5], 'Parent', f);
xlabel(h_auxiliary, 'X [a.u.]')
ylabel(h_auxiliary, 'Y [a.u.]')
title('Auxiliary Display')
box on

%Construct panel for File I/O
h_fileiopanel = uipanel('Position', [.0 .0 .25 .45], 'BackgroundColor', [1 1 1],...
    'ShadowColor', [0.7 0.7 0.7], 'Title', 'File I/O', 'FontSize', 10, 'Parent', f);
h_setDataDirectory = uicontrol(h_fileiopanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Set Data Directory',...
    'FontSize', 12,...
    'Position',[0.0,0.85,0.5,0.12],...
    'Callback',{@setDataDirectory});
h_resetAll = uicontrol(h_fileiopanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Reset DAVOS',...
    'FontSize', 12,...
    'Position',[0.5,0.85,0.5,0.12],...
    'Callback',{@resetAll});
h_dataDirectoryInfo = uicontrol(h_fileiopanel, 'Style', 'text', 'Units', 'normalized', ...
    'String', '<Data Directory>...', ...
    'FontSize', 12, ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05, 0.7, 0.9, 0.1]);
h_dataInfo = uicontrol(h_fileiopanel, 'Style', 'text', 'Units', 'normalized', ...
    'String', '<Information on the data...>', ...
    'FontSize', 12, ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05, 0.05, 0.9, 0.58]);

fileInfo = struct;
fileInfo.h_dataDirectoryInfo = h_dataDirectoryInfo;
fileInfo.h_dataInfo = h_dataInfo;

%Construct panel for Processing
h_processingpanel = uipanel('Position', [.25 .0 .25 .45], 'BackgroundColor', [1 1 1],...
    'ShadowColor', [0.7 0.7 0.7], 'Title', 'Processing', 'FontSize', 10, 'Parent', f);
h_downsample = uicontrol(h_processingpanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Down-sample (20x)',...
    'FontSize', 12,...
    'Position',[0.25,0.85,0.5,0.12],...
    'Callback',{@downsampleData});
h_removeOutliers = uicontrol(h_processingpanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Remove Outliers',...
    'FontSize', 12,...
    'Position',[0.25,0.7,0.5,0.12],...
    'Callback',{@removeOutliers});
h_robuststandardize = uicontrol(h_processingpanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Standardize',...
    'FontSize', 12,...
    'Position',[0.25,0.55,0.5,0.12],...
    'Callback',{@robuststandardizeData});
h_detectSalientFeatures = uicontrol(h_processingpanel, 'Style', 'pushbutton', 'Units', 'normalized', ...
    'String', 'Detect Features',...
    'FontSize', 12, ...
    'Position', [0.05, 0.4, 0.4, 0.12],...
    'Callback', {@detectSalientFeatures});
h_alignSeries = uicontrol(h_processingpanel, 'Style', 'pushbutton', 'Units', 'normalized', ...
    'String', 'Align Series',...
    'FontSize', 12, ...
    'Position', [0.55, 0.4, 0.4, 0.12],...
    'Callback', {@alignSeries});
h_resetSeries = uicontrol(h_processingpanel, 'Style', 'pushbutton', 'Units', 'normalized', ...
    'String', 'Reset Data',...
    'FontSize', 12, ...
    'Position', [0.25, 0.25, 0.5, 0.12],...
    'Callback', {@resetSeries});

%Construct panel for Analysis & Anomaly Detection
h_analysispanel = uipanel('Position', [.5 .0 .25 .45], 'BackgroundColor', [1 1 1],...
    'ShadowColor', [0.7 0.7 0.7], 'Title', 'Analysis & Anomaly Detection', 'FontSize', 10, 'Parent', f);
h_scatter = uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Scatter/Linear Corr.',...
    'FontSize', 12,...
    'Position',[0.25,0.85,0.5,0.12],...
    'Callback',{@scatterPlot});
h_calculatePSD = uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Power Spectrum',...
    'FontSize', 12,...
    'Position',[0.0,0.7,0.5,0.12],...
    'Callback',{@calculatePSDs});
h_autoCorrelation = uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Auto-Correlation',...
    'FontSize', 12,...
    'Position',[0.5,0.7,0.5,0.12],...
    'Callback',{@calculateAutocorr});
h_showPCAFeatures = uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Show 2D PCA Features',...
    'FontSize', 12,...
    'Position',[0.25,0.55,0.5,0.12],...
    'Callback',{@showPCAFeatures});
h_anomalykNN = uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Anomaly by kNN (ts)',...
    'FontSize', 12,...
    'Position',[0.0,0.4,0.5,0.12],...
    'Callback',{@anomalyByKNNts});
h_anomalykNN = uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Anomaly by kNN (PCA)',...
    'FontSize', 12,...
    'Position',[0.5,0.4,0.5,0.12],...
    'Callback',{@anomalyByKNNPCA});
h_1CSVMraw= uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','One-class SVM (ts)',...
    'FontSize', 12,...
    'Position',[0.0,0.25,0.5,0.12],...
    'Callback',{@oneclassSVMts});
h_1CSVMPCA= uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','One-class SVM (PCA)',...
    'FontSize', 12,...
    'Position',[0.5,0.25,0.5,0.12],...
    'Callback',{@oneclassSVMPCA});
h_anomalyLOF= uicontrol(h_analysispanel, 'Style','pushbutton','Units', 'normalized', ...
    'String','Local Outlier Factor (PCA)',...
    'FontSize', 12,...
    'Position',[0.25,0.1,0.5,0.12],...
    'Callback',{@anomalyByLOF});

%Construct panel for Results
h_resultspanel = uipanel('Position', [.75 .0 .25 .45], 'BackgroundColor', [1 1 1],...
    'ShadowColor', [0.7 0.7 0.7], 'Title', 'Results', 'FontSize', 10, 'Parent', f);
h_resultsText = uicontrol(h_resultspanel, 'Style', 'text', 'Units', 'normalized', ...
    'String', '<Information on the results...>', ...
    'FontSize', 12, ...
    'HorizontalAlignment', 'left', ...
    'Position', [0.05, 0.05, 0.9, 0.9]);

%set(f,'Toolbar','figure');  % Display the standard toolbar

% Assign the GUI a name to appear in the window title.
set(f,'Name','Data Analysis, Visualization, and Outlier-Detection Suite')

% Make the GUI visible.
set(f,'Visible','on');

plottingInfo = struct;
plottingInfo.h_timeseries = h_timeseries;
plottingInfo.h_auxiliary = h_auxiliary;

resultsInfo = struct;
resultsInfo.h_resultsText = h_resultsText;

setappdata(f, 'plottingInfo', plottingInfo);
setappdata(f, 'fileInfo', fileInfo);
setappdata(f, 'resultsInfo', resultsInfo);